### NumPy


In [2]:
import numpy as np

arr = np.array([1, 2, 3])
arr2d = np.array([(1, 2, 3), (4, 5, 6)])
print(arr)
print(arr2d)
print(arr2d.ndim)  # Dimension

[1 2 3]
[[1 2 3]
 [4 5 6]]
2


In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7])
np.save("out", a)
np.savetxt("out", a)

print(np.loadtxt("out"))

[1. 2. 3. 4. 5. 6. 7.]


#### Indexing


In [12]:
import numpy as np

arr = np.arange(1, 10, 2)
print(arr)

arr2 = arr[np.array([4, 0, 2, -1, -2])]  # Putting as an index of 'arr'
print(arr2)

[1 3 5 7 9]
[9 1 5 9 7]


In [5]:
arr = np.arange(12)
arr1 = arr.reshape(2, 6)  # Construct a 2D matrix
print(arr1)
print()

arr1 = arr.reshape(2, 2, 3)  # Construct a 3D matrix
print(arr1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [28]:
arr2 = arr.reshape(3, 4)
print(arr2)

print("Element at 1:,1:2\n", arr2[1:, 1:2])
print("Element at 1:,1:4\n", arr2[1:, 1:4])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at 1:,1:2
 [[5]
 [9]]
Element at 1:,1:4
 [[ 5  6  7]
 [ 9 10 11]]


#### Broadcasting


In [31]:
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([1, 2, 3])  # Adding on columns

print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [7]:
a = np.array(
    [("Ha", 2, 20.0), ("F", 3, 30.0), ("W", 5, 50.0)],
    dtype=[("name", (np.str_, 10)), ("age", (np.int32)), ("weight", (np.float64))],
)
print(a)
print(a["name"])
print(a["weight"])

[('Ha', 2, 20.) ('F', 3, 30.) ('W', 5, 50.)]
['Ha' 'F' 'W']
[20. 30. 50.]
